accumulate_grad_batches: 4
num_workers: 1

views: ['C10095_rgb']
clip_size: None
target_label: 'action'
learning_rate: 0.01
weight_decay: 0.0005
scheduler_step: 100
batch_size: 1
test_batch_size: 1
cemse_alpha: 0.17
train_epochs: 200
frame_features: 2048
pose_joint_features: 3
pose_joint_count: 42
model_dim: 256
dropout: 0.20
temporal_layers_count: 6
temporal_state_dim: 512

# LRU initialization
lru_max_phase:  0.314159265 # pi / 10
lru_min_radius: 0.6
lru_max_radius: 0.9

categories: ['verb', 'noun']
categories_num_classes: [25, 91]
